version: '3.9'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.25
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.25
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    volumes:
      - ./config/kibana.yml:/usr/share/kibana/config/kibana.yml
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - elasticsearch
  frontend:
    build: ./frontend
    ports:
      - "3001:3000"
    depends_on:
      - backend
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider
      - WDS_SOCKET_PORT=3001
  app-search:
    image: docker.elastic.co/enterprise-search/enterprise-search:7.17.25
    environment:
      - "elasticsearch.host=http://elasticsearch:9200"
      - "allow_es_settings_modification=true"
    ports:
      - "3002:3002"
    depends_on:
      - elasticsearch
    volumes:
      - ./config/enterprise-search.yml:/usr/share/enterprise-search/config/enterprise-search.yml
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend